export default {
    FETCH_TEXT_SAMPLES: 'FETCH_TEXT_SAMPLES',
    CLASSIFY_WORD: 'CLASSIFY_WORD',
    FETCH_TEXT_SAMPLES_SUCCESS: 'FETCH_TEXT_SAMPLES_SUCCESS',
    TEXT_SAMPLES_UPDATED: 'TEXT_SAMPLES_UPDATED'
  };